server {
  listen 80;

  location /app2/ {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /app2/index.html;
  }

  location = /app2 {
    return 302 /app2/;
  }

  location = / {
    return 200 "frontend-list ok\n";
    default_type text/plain;
  }
}
